# Experiment hyper-parameters
grid:
  - ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', 'W', 'W', 'W', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', 'W', 'W', 'W', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']
n_episodes: 100
max_steps: 400
slip_chance: 0.25
buffer_size: 1000
seed: 1
start_pos: null

# States of interest for visualisations
states:
  a: [4,7]
  b: [5, 11]
  c: [4,5]
  d: [5, 9]
  e: [4,3]
  f: [1, 5]


# Algorithm hyper-parameters
step_size: 0.001 #alpha
disc_fact: 0.9 #gamma
batch_size: 64
warmup_steps: 100
algo_type: sfqlearning
hidden_dim: null

schedule_start: 0.99
schedule_end: 0.1
schedule_decay: 0.999
