# Experiment hyper-parameters
grid:
  - ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', 'W', 'W', 'W', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', 'W', 'W', 'W', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']
n_episodes: 100
max_steps: 400
slip_chance: 0.25
buffer_size: 1000
seed: 1
start_pos: null

# Algorithm hyper-parameters
step_size: 0.001 #alpha
disc_fact: 0.9 #gamma
batch_size: 64
warmup_steps: 100
algo_type: 'off_policy' # in ['off_policy', 'on_policy']

schedule_start: 0.99
schedule_end: 0.1
schedule_decay: 0.999

