# Experiment hyper-parameters
grid:
  - ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', 'W', 'W', 'W', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W', 'W', 'W', 'W', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']
n_episodes: 1000
max_steps: 1000
slip_chance: 0.25
buffer_size: 200
seed: 1
start_pos: null

# Algorithm hyper-parameters
step_size: 0.5 #alpha
disc_fact: 0.9 #gamma
batch_size: 64
warmup_steps: 100
epsilon: 0.9
algo_type: 'on_policy' # in ['off_policy', 'on_policy']

schedule_start: 0.99
schedule_end: 0.1
schedule_decay: 0.9999

