sf_multitask_shapes_best_large_20250830_112441: sf_bert_layer_0
sf_multitask_shapes_best_large_20250831_012012: sf_bert_layer_7
sf_multitask_shapes_best_large_20250831_111944: sf_bert_layer_11
sf_multitask_shapes_best_large_elmo_20250830_113608: sf_elmo_layer_1
sf_multitask_shapes_best_large_elmo_20250831_012730: sf_elmo_layer_2
sf_multitask_shapes_best_large_isotropy_20250911_213234: sf_noise_isotropic
sf_multitask_shapes_best_large_isotropy_20250912_025424: sf_noise_anisotropic