# 'W' - wall
# ' ' - empty
# 'T' - potential goal position in the test set (placement not allowed in training)
grid:
  - ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']
  - ['W', ' ', ' ', 'T', 'W', 'T', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', 'W', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', 'W', ' ', 'T', ' ', 'W', ' ', 'T', 'W']
  - ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']
# If true, origin and destination locations will be masked and the agent will have to rely on text to extact them
goal_channel: false
num_objects: 2
resample_episodes: 1
max_steps: 200
slip_chance: 0
seed: 1

# use_fetures must reflect order of keys in features. It can be a subset, but order must be followed!
use_features: [shape, colour]
features:
  # circle, triangle, square, diamond, star, key
  shape: [ball, triangle, square, diamond, star, key]
  # green, blue, red, yellow
  colour: [red, blue, green, yellow]

task_names: [go_to, go_to_easy, pick_up, retrieve]
task_id: go_to 

go_to:
  - Go to colour shape.

go_to_easy:
  - Go to colour shape.

pick_up:
  - Pick up goal_formulation.

retrieve:
  - Retrieve goal_formulation.

default_feature: "0" 