grid:
  - ['W', 'W', 'W', 'W', 'W']
  - ['W', ' ', ' ', 'G', 'W']
  - ['W', ' ', 'A', ' ', 'W']
  - ['W', 'O', ' ', ' ', 'W']
  - ['W', 'W', 'W', 'W', 'W']


max_steps: 15
disc_fact: 0.99
slip_chance: 0
goal_resample_t: 16000
task_resample_t: null
seed: 1

features:
  # ball, triangle, square, diamond, star, key
  shape: [ball, triangle, square, diamond, star, key, door]
  # red, blue, green, yellow
  colour: [red, blue, green, yellow]

num_confounding_features: 1
one_hot: True

target_obj_spawn_likelihood: 0.25

# can contain keys and doors
reserved_combinations:
  # - shape: key
  #   colour: red
  # - shape: ball
  #   colour: green

task_progression: [linear]
tasks:
  go_to: [Go to colour shape]
  pick_up: [Pick up colour shape]
  unlock: [Unlock colour door]
  retrieve: [Retrieve colour shape]
  linear: [Pick up colour shape]