# 'W' - Wall
# ' ' - Empty
# 'A' - Agent
# 'D' - Door
# 'O' - Any object (potentially key) spawn location
# 'K' - Mandatory key spawn location. It's up to the designer to ensure all doors are unlockable (agent can reach keys belonging to all doors)
# All keys must be in the same initial room as the agent (because door colours will be randomised, prevents the case where the required key is behind a locked door)
# Grid has (x=0,y=0) in the top left corner
# (x=max,y=0) in the bottom left corner, 
# and (x=max, y=max) in the bottom right corner
grid:
  - ['W', 'W', 'W', 'W', 'W', 'W', 'W']
  - ['W', 'W', 'W', 'O', 'W', 'W', 'W']
  - ['W', 'K', 'W', 'D', 'W', 'K', 'W']
  - ['W', ' ', ' ', ' ', ' ', ' ', 'W']
  - ['W', ' ', ' ', 'W', 'W', 'D', 'W']
  - ['W', 'A', ' ', 'W', 'W', 'O', 'W']
  - ['W', 'W', 'W', 'W', 'W', 'W', 'W']

max_steps: 200
slip_chance: 0
goal_resample_t: null
task_resample_t: 1
seed: 1

features:
  # ball, triangle, square, diamond, star, key
  shape: [ball, key, door]
  # red, blue, green, yellow
  colour: [red, blue]

num_confounding_features: 0
one_hot: True

task_progression: [go_to, pick_up, unlock, retrieve]
tasks:
  go_to: [Go to colour shape]
  pick_up: [Pick up colour shape]
  unlock: [Unlock colour door]
  retrieve: [Retrieve colour shape]